### ISSUE TITLE
gotype regression

### ISSUE THREAD

**Issue by purpleidea** [alecthomas/gometalinter#358]
A few days ago, I think caused by https://github.com/alecthomas/gometalinter/commit/3eeb3c6358a5df7222c6a7f759554cc0f9729d7b cron tests started failing:

eg:
https://travis-ci.org/purpleidea/mgmt/builds/279226339

I think the issue is something related to no longer understanding build tags:

eg:

https://travis-ci.org/purpleidea/mgmt/jobs/279226341#L923

This issue might be related to:

https://github.com/alecthomas/gometalinter/issues/355
https://github.com/alecthomas/gometalinter/issues/357

Similarly but a different issue there is: https://github.com/golang/go/issues/21712

Thanks

**Comment by alecthomas** [comment]
Can you try latest master? We just merged a fix by @dnephin .

**Comment by dnephin** [comment]
I tried writing a test case that uses build tags and it didn't seem to work, so I'm guessing the #356 didn't fix it. I'm not sure how it;s supposed to work.

**Comment by alecthomas** [comment]
@purpleidea are you still having this issue?
